### ISSUE TITLE
Cannot find PagedArray

### ISSUE THREAD

**Issue by iad24** [nodes-ios/Sourcery#16]
![screen shot 2017-06-16 at 2 32 55 pm](https://user-images.githubusercontent.com/15226261/27214790-c1c31e4e-52a0-11e7-9373-cb62d3db6848.png)

Cannot find this when I downloaded your files.

**Comment by nickskull** [comment]
`PagedArray` is a dependency of Sourcery, so to be able to user Sourcery you first need to download the dependencies. Since we are using [`carthage`](https://github.com/carthage/carthage), I recommend you to download it and then at the root of this repository run `carthage bootstrap` in Terminal to download and compile the dependencies.
